/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package com.unindra.school.app.view.teacher;

import com.unindra.school.app.view.staff.*;
import com.unindra.school.app.entity.StaffResponse;
import com.unindra.school.app.model.Gender;
import com.unindra.school.app.model.LoginRequest;
import com.unindra.school.app.model.RegisterStaffRequest;
import com.unindra.school.app.service.AuthService;
import com.unindra.school.app.service.ComboBoxUtil;
import com.unindra.school.app.service.RegionService;
import com.unindra.school.app.service.StaffService;

import java.awt.Image;
import java.time.Month;
import java.time.Year;
import java.time.format.TextStyle;
import java.util.Arrays;
import java.util.ResourceBundle;
import java.util.stream.IntStream;

import javax.swing.DefaultComboBoxModel;
import javax.swing.ImageIcon;
import javax.swing.JToggleButton;

import com.unindra.school.app.util.AppManager;
import com.unindra.school.app.view.SelectRoleView;
import java.io.IOException;

import java.util.Locale;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JButton;
import javax.swing.JOptionPane;

/**
 *
 * @author rizmakiana
 */
public class TeacherLoginView extends javax.swing.JFrame {

    /**
     * Creates new form StaffLoginView
     */
    public TeacherLoginView() throws IOException {
        generateComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jTabbedPane1 = new javax.swing.JTabbedPane();
        signInPanel = new javax.swing.JPanel();
        signInLabel = new javax.swing.JLabel();
        signInusernameField = new javax.swing.JTextField();
        signInpasswordField = new javax.swing.JPasswordField();
        signInButton = new javax.swing.JButton();
        registerPanel = new javax.swing.JPanel();
        registerNameField = new javax.swing.JTextField();
        registerGenderField = new javax.swing.JComboBox<>();
        registerUsernameField = new javax.swing.JTextField();
        registerPasswordField = new javax.swing.JPasswordField();
        registerRePasswordField = new javax.swing.JPasswordField();
        registerDateField = new javax.swing.JComboBox<>();
        registerMonthField = new javax.swing.JComboBox<>();
        registerYearField = new javax.swing.JComboBox<>();
        registerEmail = new javax.swing.JTextField();
        registerPhoneNumber = new javax.swing.JTextField();
        registerButton = new javax.swing.JButton();
        registerLabel = new javax.swing.JLabel();
        provinceField = new com.unindra.school.app.components.RegionComboBox();
        regencyField = new com.unindra.school.app.components.RegionComboBox();
        districtField = new com.unindra.school.app.components.RegionComboBox();
        setting = new javax.swing.JToggleButton();
        back = new javax.swing.JButton();
        jDesktopPane1 = new javax.swing.JDesktopPane();
        jToggleButton1 = new javax.swing.JToggleButton();
        jComboBox1 = new javax.swing.JComboBox<>();
        image = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        signInPanel.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        signInLabel.setFont(new java.awt.Font("sansserif", 1, 20)); // NOI18N
        signInLabel.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        signInPanel.add(signInLabel, new org.netbeans.lib.awtextra.AbsoluteConstraints(71, 120, 250, 35));
        signInPanel.add(signInusernameField, new org.netbeans.lib.awtextra.AbsoluteConstraints(46, 242, 300, 35));
        signInPanel.add(signInpasswordField, new org.netbeans.lib.awtextra.AbsoluteConstraints(46, 287, 300, 35));

        signInButton.setFont(new java.awt.Font("sansserif", 0, 16)); // NOI18N
        signInButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                signInButtonActionPerformed(evt);
            }
        });
        signInPanel.add(signInButton, new org.netbeans.lib.awtextra.AbsoluteConstraints(46, 400, 300, 35));

        jTabbedPane1.addTab("tab1", signInPanel);

        registerPanel.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());
        registerPanel.add(registerNameField, new org.netbeans.lib.awtextra.AbsoluteConstraints(21, 210, 218, 35));
        registerPanel.add(registerGenderField, new org.netbeans.lib.awtextra.AbsoluteConstraints(244, 210, 127, 35));
        registerPanel.add(registerUsernameField, new org.netbeans.lib.awtextra.AbsoluteConstraints(21, 250, 114, 35));
        registerPanel.add(registerPasswordField, new org.netbeans.lib.awtextra.AbsoluteConstraints(140, 250, 113, 35));
        registerPanel.add(registerRePasswordField, new org.netbeans.lib.awtextra.AbsoluteConstraints(258, 250, 113, 35));
        registerPanel.add(registerDateField, new org.netbeans.lib.awtextra.AbsoluteConstraints(21, 290, 114, 35));
        registerPanel.add(registerMonthField, new org.netbeans.lib.awtextra.AbsoluteConstraints(140, 290, 113, 35));
        registerPanel.add(registerYearField, new org.netbeans.lib.awtextra.AbsoluteConstraints(258, 290, 114, 35));
        registerPanel.add(registerEmail, new org.netbeans.lib.awtextra.AbsoluteConstraints(21, 330, 173, 35));
        registerPanel.add(registerPhoneNumber, new org.netbeans.lib.awtextra.AbsoluteConstraints(199, 330, 172, 35));

        registerButton.setFont(new java.awt.Font("sansserif", 0, 16)); // NOI18N
        registerButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                registerButtonActionPerformed(evt);
            }
        });
        registerPanel.add(registerButton, new org.netbeans.lib.awtextra.AbsoluteConstraints(21, 490, 350, 35));

        registerLabel.setFont(new java.awt.Font("sansserif", 1, 20)); // NOI18N
        registerLabel.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        registerPanel.add(registerLabel, new org.netbeans.lib.awtextra.AbsoluteConstraints(71, 120, 250, 40));

        provinceField.addItemListener(new java.awt.event.ItemListener() {
            public void itemStateChanged(java.awt.event.ItemEvent evt) {
                provinceFieldItemStateChanged(evt);
            }
        });
        registerPanel.add(provinceField, new org.netbeans.lib.awtextra.AbsoluteConstraints(21, 370, 350, 35));

        regencyField.addItemListener(new java.awt.event.ItemListener() {
            public void itemStateChanged(java.awt.event.ItemEvent evt) {
                regencyFieldItemStateChanged(evt);
            }
        });
        registerPanel.add(regencyField, new org.netbeans.lib.awtextra.AbsoluteConstraints(21, 410, 173, 35));
        registerPanel.add(districtField, new org.netbeans.lib.awtextra.AbsoluteConstraints(199, 410, 173, 35));

        jTabbedPane1.addTab("tab2", registerPanel);

        getContentPane().add(jTabbedPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 392, 650));

        setting.setIcon(new javax.swing.ImageIcon(getClass().getResource("/image/settings.png"))); // NOI18N
        setting.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                settingActionPerformed(evt);
            }
        });
        getContentPane().add(setting, new org.netbeans.lib.awtextra.AbsoluteConstraints(65, 660, 40, 40));

        back.setIcon(new javax.swing.ImageIcon(getClass().getResource("/image/return.png"))); // NOI18N
        back.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                backActionPerformed(evt);
            }
        });
        getContentPane().add(back, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 660, 40, 40));

        jToggleButton1.setText("jToggleButton1");
        jToggleButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jToggleButton1ActionPerformed(evt);
            }
        });

        jComboBox1.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "English (US)", "Bahasa Indonesia" }));
        jComboBox1.addItemListener(new java.awt.event.ItemListener() {
            public void itemStateChanged(java.awt.event.ItemEvent evt) {
                jComboBox1ItemStateChanged(evt);
            }
        });

        jDesktopPane1.setLayer(jToggleButton1, javax.swing.JLayeredPane.DEFAULT_LAYER);
        jDesktopPane1.setLayer(jComboBox1, javax.swing.JLayeredPane.DEFAULT_LAYER);

        javax.swing.GroupLayout jDesktopPane1Layout = new javax.swing.GroupLayout(jDesktopPane1);
        jDesktopPane1.setLayout(jDesktopPane1Layout);
        jDesktopPane1Layout.setHorizontalGroup(
            jDesktopPane1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jDesktopPane1Layout.createSequentialGroup()
                .addGap(5, 5, 5)
                .addComponent(jToggleButton1, javax.swing.GroupLayout.PREFERRED_SIZE, 140, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(5, 5, 5)
                .addComponent(jComboBox1, javax.swing.GroupLayout.PREFERRED_SIZE, 212, javax.swing.GroupLayout.PREFERRED_SIZE))
        );
        jDesktopPane1Layout.setVerticalGroup(
            jDesktopPane1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jDesktopPane1Layout.createSequentialGroup()
                .addGap(7, 7, 7)
                .addGroup(jDesktopPane1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jToggleButton1)
                    .addComponent(jComboBox1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
        );

        getContentPane().add(jDesktopPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(110, 660, 370, 40));

        image.setIcon(new javax.swing.ImageIcon(getClass().getResource("/image/image3.png"))); // NOI18N
        getContentPane().add(image, new org.netbeans.lib.awtextra.AbsoluteConstraints(392, 0, 888, 720));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void provinceFieldItemStateChanged(java.awt.event.ItemEvent evt) {//GEN-FIRST:event_provinceFieldItemStateChanged
        
        try {
            RegionService service = new RegionService();
            
            regencyField.setItems(service.getRegencies(provinceField.getSelectedRegion().getId()));
            districtField.setItems(service.getDistricts(regencyField.getSelectedRegion().getId()));
        } catch (IOException ex) {
            Logger.getLogger(TeacherLoginView.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_provinceFieldItemStateChanged

    private void regencyFieldItemStateChanged(java.awt.event.ItemEvent evt) {//GEN-FIRST:event_regencyFieldItemStateChanged
        
        if (regencyField.getSelectedRegion() == null){
            return;
        }
        
        try {
            RegionService service = new RegionService();
            
            districtField.setItems(service.getDistricts(regencyField.getSelectedRegion().getId()));
        } catch (IOException ex) {
            Logger.getLogger(TeacherLoginView.class.getName()).log(Level.SEVERE, null, ex);
        }
                
    }//GEN-LAST:event_regencyFieldItemStateChanged

    private void setupRegionComboBox() throws IOException{

//        RegionService service = new RegionService();
//      
//        provinceField.setItems(service.getProvinces());        
//        regencyField.setItems(service.getRegencies(provinceField.getSelectedRegion().getId()));
//        districtField.setItems(service.getDistricts(regencyField.getSelectedRegion().getId()));

    }
    
    private void backActionPerformed(java.awt.event.ActionEvent evt) {// GEN-FIRST:event_backActionPerformed

        SelectRoleView view = new SelectRoleView();
        view.setVisible(true);

        this.dispose();

    }// GEN-LAST:event_backActionPerformed

    private void settingActionPerformed(java.awt.event.ActionEvent evt) {// GEN-FIRST:event_settingActionPerformed

        if (setting.isSelected()) {
            jDesktopPane1.setVisible(true);
        } else {
            jDesktopPane1.setVisible(false);
        }

    }// GEN-LAST:event_settingActionPerformed

    private void jToggleButton1ActionPerformed(java.awt.event.ActionEvent evt) {// GEN-FIRST:event_jToggleButton1ActionPerformed

        try {
            if (jToggleButton1.isSelected()) {
                AppManager.setLightMode(false);
                jToggleButton1.setText(setInternationalization("darkTheme"));
            } else {
                AppManager.setLightMode(true);
                jToggleButton1.setText(setInternationalization("lightTheme"));
            }

        } catch (Exception e) {
            e.printStackTrace();
        }

    }// GEN-LAST:event_jToggleButton1ActionPerformed

    private void jComboBox1ItemStateChanged(java.awt.event.ItemEvent evt) {// GEN-FIRST:event_jComboBox1ItemStateChanged

        if (jComboBox1.getSelectedIndex() == 1) {
            AppManager.setLocale(Locale.forLanguageTag("id-ID"));
        } else {
            AppManager.setLocale(Locale.forLanguageTag("en-US"));
        }
        initInternationalization();

    }// GEN-LAST:event_jComboBox1ItemStateChanged

    private void signInButtonActionPerformed(java.awt.event.ActionEvent evt) {// GEN-FIRST:event_signInButtonActionPerformed
        /*  
        String username = signInusernameField.getText();
        String password = new String(signInpasswordField.getPassword());
          
        LoginRequest request = new LoginRequest(username, password);
          
        try {
            String response = new AuthService().loginStaff(request);
            
            StaffResponse staff = new AuthService().getCurrentStaff();
              
            JOptionPane.showMessageDialog(this, response, setInternationalization("success"), JOptionPane.PLAIN_MESSAGE);
            */
            try {
                // StaffResponse staff = new StaffResponse();
                //StaffDashboardView view = new StaffDashboardView(staff);
                TeacherDashboardView view = new TeacherDashboardView();
                view.setVisible(true);
            
                this.dispose();

            } catch (Exception e) {
                e.printStackTrace();
            }
            /*
        } catch (IOException e) {
            JOptionPane.showMessageDialog(this, e.getMessage(), setInternationalization("error"), JOptionPane.ERROR_MESSAGE);
        }
        */
    }// GEN-LAST:event_signInButtonActionPerformed

    private void clearFormRegistration(){
        registerNameField.setText("");
        registerGenderField.setSelectedIndex(0);
        registerUsernameField.setText("");
        registerPasswordField.setText("");
        registerRePasswordField.setText("");
        registerDateField.setSelectedIndex(0);
        registerMonthField.setSelectedIndex(0);
        registerYearField.setSelectedItem("");
        registerEmail.setText("");
        registerPhoneNumber.setText("");
        provinceField.setSelectedIndex(0);
        regencyField.setSelectedIndex(0);
        districtField.setSelectedIndex(0);
    }
    
    private void registerButtonActionPerformed(java.awt.event.ActionEvent evt) {// GEN-FIRST:event_registerButtonActionPerformed
        /*
        RegisterStaffRequest request = new RegisterStaffRequest();

        request.setName(registerNameField.getText());
        request.setGender(registerGenderField.getSelectedIndex() == 0 ? Gender.MALE : Gender.FEMALE);
        request.setUsername(registerUsernameField.getText());
        request.setPassword(new String(registerPasswordField.getPassword()));
        request.setConfirmPassword(new String(registerRePasswordField.getPassword()));
        request.setBirthdate(registerDateField.getSelectedItem().toString());
        request.setBirthmonth(registerMonthField.getSelectedIndex() + 1);
        request.setBirthyear(registerYearField.getSelectedItem().toString());
        request.setEmail(registerEmail.getText());
        request.setPhoneNumber(registerPhoneNumber.getText());
        request.setDistrictId(districtField.getSelectedRegion().getId());
        
        try {
            StaffService service = new StaffService();
            
            String response = service.register(request);
            
            JOptionPane.showMessageDialog(this, response, setInternationalization("success"), JOptionPane.PLAIN_MESSAGE);
            clearFormRegistration();
        } catch (IOException e) {
            JOptionPane.showMessageDialog(this, e.getMessage(), setInternationalization("error"), JOptionPane.ERROR_MESSAGE);
        } 
        */ 
    }// GEN-LAST:event_registerButtonActionPerformed

    public void scaleButtonIcon(JToggleButton button) {
        if (button.getIcon() != null && button.getIcon() instanceof ImageIcon) {
            int width = button.getWidth();
            int height = button.getHeight();

            // Kalau belum punya ukuran (belum render), pakai preferred size
            if (width <= 0 || height <= 0) {
                width = button.getPreferredSize().width;
                height = button.getPreferredSize().height;
            }

            ImageIcon originalIcon = (ImageIcon) button.getIcon();
            Image scaledImage = originalIcon.getImage()
                    .getScaledInstance(width - 15, height - 15, Image.SCALE_SMOOTH);

            button.setIcon(new ImageIcon(scaledImage));
        }
    }

    public void scaleButtonIcon(JButton button) {
        if (button.getIcon() != null && button.getIcon() instanceof ImageIcon) {
            int width = button.getWidth();
            int height = button.getHeight();

            // Kalau belum punya ukuran (belum render), pakai preferred size
            if (width <= 0 || height <= 0) {
                width = button.getPreferredSize().width;
                height = button.getPreferredSize().height;
            }

            ImageIcon originalIcon = (ImageIcon) button.getIcon();
            Image scaledImage = originalIcon.getImage()
                    .getScaledInstance(width - 15, height - 15, Image.SCALE_SMOOTH);

            button.setIcon(new ImageIcon(scaledImage));
        }
    }

    public String setInternationalization(String key) {

        ResourceBundle bundle = ResourceBundle.getBundle("message", AppManager.getLocale());

        return bundle.getString(key);
    }

    public void initInternationalization() {
        jTabbedPane1.setTitleAt(0, setInternationalization("login"));
        jTabbedPane1.setTitleAt(1, setInternationalization("register"));

        signInLabel.setText(setInternationalization("sign.in"));

        signInusernameField.putClientProperty("JTextField.placeholderText", setInternationalization("input.username"));
        signInpasswordField.putClientProperty("JTextField.placeholderText", setInternationalization("input.password"));

        signInButton.setText(setInternationalization("sign.in"));

        registerLabel.setText(setInternationalization("register"));
        registerButton.setText(setInternationalization("register"));

        registerNameField.putClientProperty("JTextField.placeholderText", setInternationalization("input.name"));
        String[] genders = new String[] { setInternationalization("male"), setInternationalization("female") };
        registerGenderField.setModel(new DefaultComboBoxModel<>(genders));
        registerUsernameField.putClientProperty("JTextField.placeholderText",
                setInternationalization("input.username"));
        registerPasswordField.putClientProperty("JTextField.placeholderText",
                setInternationalization("input.password"));
        registerRePasswordField.putClientProperty("JTextField.placeholderText",
                setInternationalization("input.confirm.password"));
        registerEmail.putClientProperty("JTextField.placeholderText", setInternationalization("input.email"));
        registerPhoneNumber.putClientProperty("JTextField.placeholderText",
                setInternationalization("input.phone.number"));
        registerMonthField.setModel(new DefaultComboBoxModel<>(ComboBoxUtil.getMonthList()));
        
        boolean lightMode = AppManager.getLightMode();

        if (lightMode) {
            jToggleButton1.setSelected(false);
            jToggleButton1.setText(setInternationalization("lightTheme"));
        } else {
            jToggleButton1.setSelected(true);
            jToggleButton1.setText(setInternationalization("darkTheme"));
        }
    }

    public void generateComponents() throws IOException {
        initComponents();
        setLocationRelativeTo(null);
        initInternationalization();
        jTabbedPane1.putClientProperty("JTabbedPane.tabAreaAlignment", "fill");
        scaleButtonIcon(setting);
        scaleButtonIcon(back);
        registerDateField.setModel(new DefaultComboBoxModel<>(ComboBoxUtil.getDateList()));
        registerYearField.setModel(new DefaultComboBoxModel<>(ComboBoxUtil.getYearListTeacher()));

        boolean lightMode = AppManager.getLightMode();

        if (lightMode) {
            jToggleButton1.setSelected(false);
            jToggleButton1.setText(setInternationalization("lightTheme"));
        } else {
            jToggleButton1.setSelected(true);
            jToggleButton1.setText(setInternationalization("darkTheme"));
        }

        if (AppManager.getLocale().getLanguage().equals("en")) {
            jComboBox1.setSelectedIndex(0);
        } else {
            jComboBox1.setSelectedIndex(1);
        }

        jDesktopPane1.setVisible(false);
       
        setupRegionComboBox();
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton back;
    private com.unindra.school.app.components.RegionComboBox districtField;
    private javax.swing.JLabel image;
    private javax.swing.JComboBox<String> jComboBox1;
    private javax.swing.JDesktopPane jDesktopPane1;
    private javax.swing.JTabbedPane jTabbedPane1;
    private javax.swing.JToggleButton jToggleButton1;
    private com.unindra.school.app.components.RegionComboBox provinceField;
    private com.unindra.school.app.components.RegionComboBox regencyField;
    private javax.swing.JButton registerButton;
    private javax.swing.JComboBox<String> registerDateField;
    private javax.swing.JTextField registerEmail;
    private javax.swing.JComboBox<String> registerGenderField;
    private javax.swing.JLabel registerLabel;
    private javax.swing.JComboBox<String> registerMonthField;
    private javax.swing.JTextField registerNameField;
    private javax.swing.JPanel registerPanel;
    private javax.swing.JPasswordField registerPasswordField;
    private javax.swing.JTextField registerPhoneNumber;
    private javax.swing.JPasswordField registerRePasswordField;
    private javax.swing.JTextField registerUsernameField;
    private javax.swing.JComboBox<String> registerYearField;
    private javax.swing.JToggleButton setting;
    private javax.swing.JButton signInButton;
    private javax.swing.JLabel signInLabel;
    private javax.swing.JPanel signInPanel;
    private javax.swing.JPasswordField signInpasswordField;
    private javax.swing.JTextField signInusernameField;
    // End of variables declaration//GEN-END:variables
}
