/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package com.unindra.school.app.view.teacher;

import com.formdev.flatlaf.extras.components.FlatTriStateCheckBox;
import com.unindra.school.app.util.AppManager;
import java.awt.Color;
import java.awt.FlowLayout;
import java.awt.Image;
import java.io.IOException;
import java.text.MessageFormat;
import java.util.Locale;
import java.util.ResourceBundle;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.DefaultCellEditor;
import javax.swing.ImageIcon;
import javax.swing.JButton;
import javax.swing.JLabel;
import javax.swing.JPanel;
import javax.swing.JToggleButton;
import javax.swing.table.DefaultTableCellRenderer;
import javax.swing.table.DefaultTableModel;
import javax.swing.table.TableColumn;
import javax.swing.table.TableColumnModel;

/**
 *
 * @author rizmakiana
 */
public class TeacherDashboardView extends javax.swing.JFrame {

    /**
     * Creates new form TeacherDashboardView
     */
    public TeacherDashboardView() {
        generateComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        back = new javax.swing.JButton();
        settings = new javax.swing.JToggleButton();
        layer = new javax.swing.JDesktopPane();
        jTabbedPane1 = new javax.swing.JTabbedPane();
        scorePanel = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        scoreTable = new javax.swing.JTable();
        scorePanelSectionList = new javax.swing.JComboBox<>();
        scorePanelPrintButton = new javax.swing.JButton();
        scorePanelSaveButton = new javax.swing.JButton();
        presencePanel = new javax.swing.JPanel();
        jScrollPane2 = new javax.swing.JScrollPane();
        presenceTable = new javax.swing.JTable();
        presencePanelSaveButton = new javax.swing.JButton();
        presencePanelSectionList = new javax.swing.JComboBox<>();
        jComboBox1 = new javax.swing.JComboBox<>();
        presenceRecapPanel = new javax.swing.JPanel();
        jScrollPane3 = new javax.swing.JScrollPane();
        presenceRecapTable = new javax.swing.JTable();
        presenceRecapPanelPrintButton = new javax.swing.JButton();
        presenceRecapSectionList = new javax.swing.JComboBox<>();
        jTabbedPane2 = new javax.swing.JTabbedPane();
        jPanel4 = new javax.swing.JPanel();
        jScrollPane4 = new javax.swing.JScrollPane();
        jTable1 = new javax.swing.JTable();
        jComboBox2 = new javax.swing.JComboBox<>();
        jButton1 = new javax.swing.JButton();
        jPanel5 = new javax.swing.JPanel();
        jScrollPane5 = new javax.swing.JScrollPane();
        jTable2 = new javax.swing.JTable();
        settingPanel = new javax.swing.JInternalFrame();
        jToggleButton8 = new javax.swing.JToggleButton();
        jComboBox4 = new javax.swing.JComboBox<>();
        jButton5 = new javax.swing.JButton();
        settingPanelNameLabel = new javax.swing.JLabel();
        settingPanelUsernameLabel = new javax.swing.JLabel();
        settingPanelGenderLabel = new javax.swing.JLabel();
        settingPanelEmailLabel = new javax.swing.JLabel();
        settingPanelPhoneNumberLabel = new javax.swing.JLabel();
        settingPanelBirthplaceLabel = new javax.swing.JLabel();
        settingPanelPhoneNumberField = new javax.swing.JTextField();
        settingPanelEmailField = new javax.swing.JTextField();
        settingPanelUsernameField = new javax.swing.JTextField();
        settingPanelNameField = new javax.swing.JTextField();
        settingPanelPasswordLabel = new javax.swing.JLabel();
        settingPanelPasswordField = new javax.swing.JPasswordField();
        settingPanelGenderList = new javax.swing.JComboBox<>();
        settingPanelProvinceList = new com.unindra.school.app.components.RegionComboBox();
        settingPanelRegencyList = new com.unindra.school.app.components.RegionComboBox();
        settingPanelDistrictList = new com.unindra.school.app.components.RegionComboBox();
        jLabel3 = new javax.swing.JLabel();
        settingPanelDate = new javax.swing.JComboBox<>();
        settingPanelMonth = new javax.swing.JComboBox<>();
        settingPanelYear = new javax.swing.JComboBox<>();
        jLabel4 = new javax.swing.JLabel();
        settingPanelnewPassword = new javax.swing.JPasswordField();
        jLabel5 = new javax.swing.JLabel();
        settingPanelConfirmNewPassword = new javax.swing.JPasswordField();
        myProfile = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        jLabel1.setText("Test");
        getContentPane().add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(980, 680, 300, 40));

        back.setIcon(new javax.swing.ImageIcon(getClass().getResource("/image/return.png"))); // NOI18N
        back.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                backActionPerformed(evt);
            }
        });
        getContentPane().add(back, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 660, 40, 40));

        settings.setIcon(new javax.swing.ImageIcon(getClass().getResource("/image/settings.png"))); // NOI18N
        settings.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                settingsActionPerformed(evt);
            }
        });
        getContentPane().add(settings, new org.netbeans.lib.awtextra.AbsoluteConstraints(65, 660, 40, 40));

        layer.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        scorePanel.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        scoreTable.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null}
            },
            new String [] {
                "ID", "Name", "Task score", "Mid Test Score", "Last Test Score", "Final Score"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false, true, true, true, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        jScrollPane1.setViewportView(scoreTable);
        if (scoreTable.getColumnModel().getColumnCount() > 0) {
            scoreTable.getColumnModel().getColumn(0).setResizable(false);
            scoreTable.getColumnModel().getColumn(1).setResizable(false);
            scoreTable.getColumnModel().getColumn(2).setResizable(false);
            scoreTable.getColumnModel().getColumn(3).setResizable(false);
            scoreTable.getColumnModel().getColumn(4).setResizable(false);
            scoreTable.getColumnModel().getColumn(5).setResizable(false);
        }

        scorePanel.add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 50, 1200, 520));

        scorePanelSectionList.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Ilmu Pengetahuan Alam 10 A" }));
        scorePanel.add(scorePanelSectionList, new org.netbeans.lib.awtextra.AbsoluteConstraints(780, 15, 230, -1));

        scorePanelPrintButton.setText("jButton1");
        scorePanel.add(scorePanelPrintButton, new org.netbeans.lib.awtextra.AbsoluteConstraints(1120, 15, 100, -1));

        scorePanelSaveButton.setText("jButton2");
        scorePanel.add(scorePanelSaveButton, new org.netbeans.lib.awtextra.AbsoluteConstraints(1015, 15, 100, -1));

        jTabbedPane1.addTab("tab1", scorePanel);

        presencePanel.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        presenceTable.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null}
            },
            new String [] {
                "ID", "Name", "Present"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.Object.class, java.lang.Object.class, java.lang.Boolean.class
            };
            boolean[] canEdit = new boolean [] {
                false, false, false
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        jScrollPane2.setViewportView(presenceTable);
        if (presenceTable.getColumnModel().getColumnCount() > 0) {
            presenceTable.getColumnModel().getColumn(0).setResizable(false);
            presenceTable.getColumnModel().getColumn(1).setResizable(false);
            presenceTable.getColumnModel().getColumn(2).setResizable(false);
        }

        presencePanel.add(jScrollPane2, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 50, 1200, 520));

        presencePanelSaveButton.setText("jButton3");
        presencePanel.add(presencePanelSaveButton, new org.netbeans.lib.awtextra.AbsoluteConstraints(1120, 15, 100, -1));

        presencePanelSectionList.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Ilmu Pengetahuan Alam 10 A" }));
        presencePanel.add(presencePanelSectionList, new org.netbeans.lib.awtextra.AbsoluteConstraints(725, 15, 240, -1));

        jComboBox1.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Pertemuan 1" }));
        presencePanel.add(jComboBox1, new org.netbeans.lib.awtextra.AbsoluteConstraints(970, 15, 140, -1));

        jTabbedPane1.addTab("tab2", presencePanel);

        presenceRecapPanel.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        presenceRecapTable.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null}
            },
            new String [] {
                "ID", "Name", "1", "2", "3", "4", "5", "6", "7", "8", "9", "10", "11", "12", "13", "14", "15", "16", "Presence", "Percent"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.Object.class, java.lang.Object.class, java.lang.Boolean.class, java.lang.Boolean.class, java.lang.Boolean.class, java.lang.Boolean.class, java.lang.Boolean.class, java.lang.Boolean.class, java.lang.Boolean.class, java.lang.Boolean.class, java.lang.Boolean.class, java.lang.Boolean.class, java.lang.Boolean.class, java.lang.Boolean.class, java.lang.Boolean.class, java.lang.Boolean.class, java.lang.Boolean.class, java.lang.Boolean.class, java.lang.Object.class, java.lang.Object.class
            };
            boolean[] canEdit = new boolean [] {
                false, false, false, false, false, false, false, false, false, false, false, false, false, false, false, false, false, false, false, false
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        jScrollPane3.setViewportView(presenceRecapTable);
        if (presenceRecapTable.getColumnModel().getColumnCount() > 0) {
            presenceRecapTable.getColumnModel().getColumn(0).setResizable(false);
            presenceRecapTable.getColumnModel().getColumn(0).setPreferredWidth(120);
            presenceRecapTable.getColumnModel().getColumn(1).setResizable(false);
            presenceRecapTable.getColumnModel().getColumn(1).setPreferredWidth(200);
            presenceRecapTable.getColumnModel().getColumn(2).setResizable(false);
            presenceRecapTable.getColumnModel().getColumn(2).setPreferredWidth(20);
            presenceRecapTable.getColumnModel().getColumn(3).setResizable(false);
            presenceRecapTable.getColumnModel().getColumn(3).setPreferredWidth(20);
            presenceRecapTable.getColumnModel().getColumn(4).setResizable(false);
            presenceRecapTable.getColumnModel().getColumn(4).setPreferredWidth(20);
            presenceRecapTable.getColumnModel().getColumn(5).setResizable(false);
            presenceRecapTable.getColumnModel().getColumn(5).setPreferredWidth(20);
            presenceRecapTable.getColumnModel().getColumn(6).setResizable(false);
            presenceRecapTable.getColumnModel().getColumn(6).setPreferredWidth(20);
            presenceRecapTable.getColumnModel().getColumn(7).setResizable(false);
            presenceRecapTable.getColumnModel().getColumn(7).setPreferredWidth(20);
            presenceRecapTable.getColumnModel().getColumn(8).setResizable(false);
            presenceRecapTable.getColumnModel().getColumn(8).setPreferredWidth(20);
            presenceRecapTable.getColumnModel().getColumn(9).setResizable(false);
            presenceRecapTable.getColumnModel().getColumn(9).setPreferredWidth(20);
            presenceRecapTable.getColumnModel().getColumn(10).setResizable(false);
            presenceRecapTable.getColumnModel().getColumn(10).setPreferredWidth(20);
            presenceRecapTable.getColumnModel().getColumn(11).setResizable(false);
            presenceRecapTable.getColumnModel().getColumn(11).setPreferredWidth(20);
            presenceRecapTable.getColumnModel().getColumn(12).setResizable(false);
            presenceRecapTable.getColumnModel().getColumn(12).setPreferredWidth(20);
            presenceRecapTable.getColumnModel().getColumn(13).setResizable(false);
            presenceRecapTable.getColumnModel().getColumn(13).setPreferredWidth(20);
            presenceRecapTable.getColumnModel().getColumn(14).setResizable(false);
            presenceRecapTable.getColumnModel().getColumn(14).setPreferredWidth(20);
            presenceRecapTable.getColumnModel().getColumn(15).setResizable(false);
            presenceRecapTable.getColumnModel().getColumn(15).setPreferredWidth(20);
            presenceRecapTable.getColumnModel().getColumn(16).setResizable(false);
            presenceRecapTable.getColumnModel().getColumn(16).setPreferredWidth(20);
            presenceRecapTable.getColumnModel().getColumn(17).setResizable(false);
            presenceRecapTable.getColumnModel().getColumn(17).setPreferredWidth(20);
            presenceRecapTable.getColumnModel().getColumn(18).setResizable(false);
            presenceRecapTable.getColumnModel().getColumn(19).setResizable(false);
        }

        presenceRecapPanel.add(jScrollPane3, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 50, 1190, 510));

        presenceRecapPanelPrintButton.setText("jButton4");
        presenceRecapPanelPrintButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                presenceRecapPanelPrintButtonActionPerformed(evt);
            }
        });
        presenceRecapPanel.add(presenceRecapPanelPrintButton, new org.netbeans.lib.awtextra.AbsoluteConstraints(1110, 15, 100, -1));

        presenceRecapSectionList.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Ilmu Pengetahuan Alam 10 A" }));
        presenceRecapPanel.add(presenceRecapSectionList, new org.netbeans.lib.awtextra.AbsoluteConstraints(860, 15, 240, -1));

        jTabbedPane1.addTab("tab3", presenceRecapPanel);

        jPanel4.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jTable1.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jScrollPane4.setViewportView(jTable1);

        jPanel4.add(jScrollPane4, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 50, 1200, 470));

        jComboBox2.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));
        jPanel4.add(jComboBox2, new org.netbeans.lib.awtextra.AbsoluteConstraints(880, 15, 220, -1));

        jButton1.setText("jButton1");
        jPanel4.add(jButton1, new org.netbeans.lib.awtextra.AbsoluteConstraints(1110, 15, 110, -1));

        jTabbedPane2.addTab("tab1", jPanel4);

        jPanel5.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jTable2.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jScrollPane5.setViewportView(jTable2);

        jPanel5.add(jScrollPane5, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 50, 1200, 470));

        jTabbedPane2.addTab("tab2", jPanel5);

        jTabbedPane1.addTab("tab4", jTabbedPane2);

        layer.add(jTabbedPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 20, 1240, 630));

        settingPanel.setClosable(true);
        settingPanel.setDefaultCloseOperation(javax.swing.WindowConstants.HIDE_ON_CLOSE);
        settingPanel.setVisible(true);
        settingPanel.getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jToggleButton8.setText("jToggleButton8");
        jToggleButton8.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jToggleButton8ActionPerformed(evt);
            }
        });
        settingPanel.getContentPane().add(jToggleButton8, new org.netbeans.lib.awtextra.AbsoluteConstraints(24, 520, 150, 30));

        jComboBox4.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "English (US)", "Bahasa Indonesia" }));
        jComboBox4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jComboBox4ActionPerformed(evt);
            }
        });
        settingPanel.getContentPane().add(jComboBox4, new org.netbeans.lib.awtextra.AbsoluteConstraints(179, 520, 225, 30));

        jButton5.setText("Save");
        settingPanel.getContentPane().add(jButton5, new org.netbeans.lib.awtextra.AbsoluteConstraints(24, 485, 380, 30));

        settingPanelNameLabel.setFont(new java.awt.Font("Adwaita Sans", 0, 14)); // NOI18N
        settingPanelNameLabel.setText("Name");
        settingPanel.getContentPane().add(settingPanelNameLabel, new org.netbeans.lib.awtextra.AbsoluteConstraints(24, 60, 120, 30));

        settingPanelUsernameLabel.setText("Username");
        settingPanel.getContentPane().add(settingPanelUsernameLabel, new org.netbeans.lib.awtextra.AbsoluteConstraints(24, 165, 120, 30));

        settingPanelGenderLabel.setText("Gender");
        settingPanel.getContentPane().add(settingPanelGenderLabel, new org.netbeans.lib.awtextra.AbsoluteConstraints(24, 130, 120, 30));

        settingPanelEmailLabel.setText("E-mail");
        settingPanel.getContentPane().add(settingPanelEmailLabel, new org.netbeans.lib.awtextra.AbsoluteConstraints(24, 200, 120, 30));

        settingPanelPhoneNumberLabel.setText("Phone number");
        settingPanel.getContentPane().add(settingPanelPhoneNumberLabel, new org.netbeans.lib.awtextra.AbsoluteConstraints(24, 235, 120, 30));

        settingPanelBirthplaceLabel.setText("Birthplace");
        settingPanel.getContentPane().add(settingPanelBirthplaceLabel, new org.netbeans.lib.awtextra.AbsoluteConstraints(24, 270, 120, 30));

        settingPanelPhoneNumberField.setText("jTextField1");
        settingPanel.getContentPane().add(settingPanelPhoneNumberField, new org.netbeans.lib.awtextra.AbsoluteConstraints(154, 235, 250, 30));

        settingPanelEmailField.setText("jTextField2");
        settingPanel.getContentPane().add(settingPanelEmailField, new org.netbeans.lib.awtextra.AbsoluteConstraints(154, 200, 250, 30));

        settingPanelUsernameField.setText("jTextField4");
        settingPanel.getContentPane().add(settingPanelUsernameField, new org.netbeans.lib.awtextra.AbsoluteConstraints(154, 165, 250, 30));

        settingPanelNameField.setText("jTextField5");
        settingPanel.getContentPane().add(settingPanelNameField, new org.netbeans.lib.awtextra.AbsoluteConstraints(154, 60, 250, 30));

        settingPanelPasswordLabel.setText("Password");
        settingPanel.getContentPane().add(settingPanelPasswordLabel, new org.netbeans.lib.awtextra.AbsoluteConstraints(24, 340, 120, 30));

        settingPanelPasswordField.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                settingPanelPasswordFieldKeyReleased(evt);
            }
        });
        settingPanel.getContentPane().add(settingPanelPasswordField, new org.netbeans.lib.awtextra.AbsoluteConstraints(154, 340, 250, 30));

        settingPanelGenderList.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));
        settingPanel.getContentPane().add(settingPanelGenderList, new org.netbeans.lib.awtextra.AbsoluteConstraints(154, 130, 250, 30));
        settingPanel.getContentPane().add(settingPanelProvinceList, new org.netbeans.lib.awtextra.AbsoluteConstraints(154, 270, 250, 30));
        settingPanel.getContentPane().add(settingPanelRegencyList, new org.netbeans.lib.awtextra.AbsoluteConstraints(154, 305, 122, 30));
        settingPanel.getContentPane().add(settingPanelDistrictList, new org.netbeans.lib.awtextra.AbsoluteConstraints(281, 305, 123, 30));

        jLabel3.setText("Birthdate");
        settingPanel.getContentPane().add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(24, 95, 120, 30));

        settingPanelDate.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));
        settingPanel.getContentPane().add(settingPanelDate, new org.netbeans.lib.awtextra.AbsoluteConstraints(154, 95, 80, 30));

        settingPanelMonth.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));
        settingPanel.getContentPane().add(settingPanelMonth, new org.netbeans.lib.awtextra.AbsoluteConstraints(239, 95, 80, 30));

        settingPanelYear.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));
        settingPanel.getContentPane().add(settingPanelYear, new org.netbeans.lib.awtextra.AbsoluteConstraints(324, 95, 80, 30));

        jLabel4.setText("New password");
        settingPanel.getContentPane().add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(24, 375, 120, 30));
        settingPanel.getContentPane().add(settingPanelnewPassword, new org.netbeans.lib.awtextra.AbsoluteConstraints(154, 375, 250, 30));

        jLabel5.setText("Confirm new password");
        settingPanel.getContentPane().add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(24, 410, 120, 30));
        settingPanel.getContentPane().add(settingPanelConfirmNewPassword, new org.netbeans.lib.awtextra.AbsoluteConstraints(154, 410, 250, 30));

        myProfile.setFont(new java.awt.Font("Adwaita Sans", 1, 16)); // NOI18N
        myProfile.setText("jLabel2");
        settingPanel.getContentPane().add(myProfile, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 15, 380, 30));

        layer.add(settingPanel, new org.netbeans.lib.awtextra.AbsoluteConstraints(110, 100, 440, 600));

        getContentPane().add(layer, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 1280, 720));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    public void scaleButtonIcon(JToggleButton button) {
        if (button.getIcon() != null && button.getIcon() instanceof ImageIcon) {
            int width = button.getWidth();
            int height = button.getHeight();

            // Kalau belum punya ukuran (belum render), pakai preferred size
            if (width <= 0 || height <= 0) {
                width = button.getPreferredSize().width;
                height = button.getPreferredSize().height;
            }

            ImageIcon originalIcon = (ImageIcon) button.getIcon();
            Image scaledImage = originalIcon.getImage()
                    .getScaledInstance(width - 15, height - 15, Image.SCALE_SMOOTH);

            button.setIcon(new ImageIcon(scaledImage));
        }
    }
    
    public void scaleButtonIcon(JButton button) {
        if (button.getIcon() != null && button.getIcon() instanceof ImageIcon) {
            int width = button.getWidth();
            int height = button.getHeight();

            // Kalau belum punya ukuran (belum render), pakai preferred size
            if (width <= 0 || height <= 0) {
                width = button.getPreferredSize().width;
                height = button.getPreferredSize().height;
            }

            ImageIcon originalIcon = (ImageIcon) button.getIcon();
            Image scaledImage = originalIcon.getImage()
                    .getScaledInstance(width - 15, height - 15, Image.SCALE_SMOOTH);

            button.setIcon(new ImageIcon(scaledImage));
        }
    }
    
    private void setUpPresenceRecapTable() {
        // kolom 2 s/d 17 = pertemuan (pakai tri-state checkbox)
        for (int i = 2; i < 18; i++) {
            TableColumn column = presenceRecapTable.getColumnModel().getColumn(i);

            // Editor: tri-state
            column.setCellEditor(new DefaultCellEditor(new FlatTriStateCheckBox()));

            // Renderer: tri-state
            column.setCellRenderer((table, value, isSelected, hasFocus, row, col) -> {
                FlatTriStateCheckBox checkBox = new FlatTriStateCheckBox();

                if (value == null) {
                    checkBox.setState(FlatTriStateCheckBox.State.INDETERMINATE);
                } else if (Boolean.TRUE.equals(value)) {
                    checkBox.setState(FlatTriStateCheckBox.State.SELECTED);
                } else {
                    checkBox.setState(FlatTriStateCheckBox.State.UNSELECTED);
                }

                checkBox.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
                checkBox.setBackground(isSelected ? table.getSelectionBackground() : table.getBackground());
                return checkBox;
            });
        }

        // --- Renderer untuk kolom recap (contoh kolom 18) & persentase (kolom 19) ---
        DefaultTableCellRenderer centerRenderer = new DefaultTableCellRenderer();
        centerRenderer.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);

        presenceRecapTable.getColumnModel().getColumn(18).setCellRenderer(centerRenderer); // "5/8"
        presenceRecapTable.getColumnModel().getColumn(19).setCellRenderer(centerRenderer); // "62%"
    }


    
    private void loadPresenceRecapDataDummy() {
        DefaultTableModel model = (DefaultTableModel) presenceRecapTable.getModel();
        model.setRowCount(0); // clear dulu

        for (int i = 1; i <= 30; i++) {
            Object[] rowData = new Object[20]; // 0-18

            // ID dan nama
            rowData[0] = String.format("S%03d", i);
            rowData[1] = "Siswa " + i;

            int hadir = 0, total = 0;

            // Pertemuan 1–12 (kolom 2–13)
            for (int c = 2; c <= 13; c++) {
                // contoh random aja siapa yang hadir
                Boolean isHadir = (Math.random() > 0.2); // 80% hadir
                rowData[c] = isHadir;
                total++;
                if (Boolean.TRUE.equals(isHadir)) hadir++;
            }

            // Pertemuan 13–16 (kolom 14–17) masih null
            for (int c = 14; c <= 17; c++) {
                rowData[c] = null;
            }

            // Progress (kolom 18)
            int progress = (total == 0) ? 0 : (hadir * 100 / total);

            String ratio = String.format("%d/%d", hadir, total);
            String percentage = String.format("%d%%", progress);

            rowData[18] = ratio;
            rowData[19] = percentage;

            model.addRow(rowData);
        }
    }

    private void presenceRecapPanelPrintButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_presenceRecapPanelPrintButtonActionPerformed
        
        System.out.println("Triggered");
        int total = 0;
        TableColumnModel model = presenceRecapTable.getColumnModel();
        for(int i = 0; i < model.getColumnCount(); i++ ){
            int k = model.getColumn(i).getWidth();
            String f = (String) model.getColumn(i).getHeaderValue();
            total += k;
            System.out.println(f + " = " + k);
        }
        System.out.println("total = " + total);
        
    }//GEN-LAST:event_presenceRecapPanelPrintButtonActionPerformed

    private void backActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_backActionPerformed

        try {
            TeacherLoginView view = new TeacherLoginView();
            view.setVisible(true);

            this.dispose();
        } catch (IOException ex) {
            Logger.getLogger(TeacherDashboardView.class.getName()).log(Level.SEVERE, null, ex);
        }

    }//GEN-LAST:event_backActionPerformed

    private void settingsActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_settingsActionPerformed

        if(settings.isSelected()){
            /*
            try {
                setUpProfile();
            } catch (IOException ex) {
                Logger.getLogger(StaffDashboardView.class.getName()).log(Level.SEVERE, null, ex);
            }*/
            settingPanel.setVisible(true);
        } else {
            settingPanel.setVisible(false);
        }

    }//GEN-LAST:event_settingsActionPerformed

    private void jToggleButton8ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jToggleButton8ActionPerformed

        try {
            if (jToggleButton8.isSelected()) {
                AppManager.setLightMode(false);
                jToggleButton8.setText(setInternationalization("darkTheme"));
            } else {
                AppManager.setLightMode(true);
                jToggleButton8.setText(setInternationalization("lightTheme"));
            }

            Color color = jTabbedPane1.getBackground();
            layer.setBackground(color);
        } catch (Exception e) {
            e.printStackTrace();
        }

    }//GEN-LAST:event_jToggleButton8ActionPerformed

    private void jComboBox4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jComboBox4ActionPerformed

        if (jComboBox4.getSelectedIndex() == 1){
            AppManager.setLocale(Locale.forLanguageTag("id-ID"));
        } else {
            AppManager.setLocale(Locale.forLanguageTag("en-US"));
        }
        initInternationalization();
        /*
        settingPanelDate.setSelectedItem(staffResponse.getBirthDate().getDayOfMonth());
        settingPanelMonth.setSelectedIndex(staffResponse.getBirthDate().getMonthValue() + 1);
        settingPanelYear.setSelectedItem(staffResponse.getBirthDate().getYear());
        */

    }//GEN-LAST:event_jComboBox4ActionPerformed

    private void settingPanelPasswordFieldKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_settingPanelPasswordFieldKeyReleased

        boolean isPasswordEmpty = settingPanelPasswordField.getPassword().length == 0;

        settingPanelnewPassword.setEnabled(!isPasswordEmpty);
        settingPanelConfirmNewPassword.setEnabled(!isPasswordEmpty);

        if (isPasswordEmpty) {
            settingPanelnewPassword.setText("");
            settingPanelConfirmNewPassword.setText("");
        }

    }//GEN-LAST:event_settingPanelPasswordFieldKeyReleased

    private void setUpHeaderScoreTable(){
        String[] header = new String[]{
            setInternationalization("student.id"),
            setInternationalization("name"),
            setInternationalization("task.score"),
            setInternationalization("mid.test.score"),
            setInternationalization("last.test.score"),
            setInternationalization("final.score")
        };
        
        TableColumnModel model = scoreTable.getColumnModel();
        for (int i = 0; i < header.length; i++){
            model.getColumn(i).setHeaderValue(header[i]);
        }
    }
    
    private void setUpHeaderPresenceTable(){
        String[] header = new String[]{
            setInternationalization("student.id"),
            setInternationalization("name"),
            setInternationalization("presence")
        };
        
        TableColumnModel model = presenceTable.getColumnModel();
        for (int i = 0; i < header.length; i++){
            model.getColumn(i).setHeaderValue(header[i]);
        }
    }
    
    private void setUpHeaderRecapPresenceTable(){
        String[] header = new String[]{
            setInternationalization("student.id"),
            setInternationalization("name"),
            setInternationalization("presence"),
            setInternationalization("percent")
        };
        int k = 0;
        TableColumnModel model = presenceRecapTable.getColumnModel();
        for (int i = 0; i < 2; i++){
            model.getColumn(i).setHeaderValue(header[i]);
            k++;
        }
        for (int i = 18; i < 20; i++){
            model.getColumn(i).setHeaderValue(header[k]);
            k++;
        }
        
    }
    
    public String setInternationalization(String key) {

        ResourceBundle bundle = ResourceBundle.getBundle("message", AppManager.getLocale());

        return bundle.getString(key);
    }
    
    public String setInternationalization(String key, String value) {

        ResourceBundle bundle = ResourceBundle.getBundle("message", AppManager.getLocale());

        String template =  bundle.getString(key);
        return MessageFormat.format(template, value);
    }
    
    private void initInternationalization(){
        
        jLabel1.setText(setInternationalization("greeting.message", "Rizky"));
        
        jTabbedPane1.setTitleAt(0, setInternationalization("score"));
        jTabbedPane1.setTitleAt(1, setInternationalization("presence"));
        jTabbedPane1.setTitleAt(2, setInternationalization("presence.recap"));
        jTabbedPane1.setTitleAt(3, setInternationalization("homeroom.dashboard"));
        
        jTabbedPane2.setTitleAt(0, setInternationalization("presence.recap"));
        jTabbedPane2.setTitleAt(1, setInternationalization("score.recap"));
        
        boolean isLightMode = AppManager.getLightMode();
        if (isLightMode) {
            jToggleButton8.setText(setInternationalization("darkTheme"));
        } else {
            jToggleButton8.setText(setInternationalization("lightTheme"));
        }
        
        scorePanelSaveButton.setText(setInternationalization("save"));
        scorePanelPrintButton.setText(setInternationalization("print"));
        
        presencePanelSaveButton.setText(setInternationalization("save"));
        
        presenceRecapPanelPrintButton.setText(setInternationalization("print"));
        
        setUpHeaderScoreTable();
        setUpHeaderPresenceTable();
        setUpHeaderRecapPresenceTable();
        
    }
    
    private void generateComponents(){
        initComponents();
        setLocationRelativeTo(null);
        initInternationalization();
        
        Color color = jTabbedPane1.getBackground();
        layer.setBackground(color);
       
        jTabbedPane1.putClientProperty("JTabbedPane.tabHeight", 50);
        ImageIcon logo = new ImageIcon(getClass().getResource("/image/icon.png"));
        JLabel logoLabel = new JLabel(logo);
        
        jTabbedPane1.putClientProperty("JTabbedPane.leadingComponent", logoLabel);
        
        JPanel trailingPanel = new JPanel(new FlowLayout(FlowLayout.RIGHT, 10, 0));
        trailingPanel.add(jLabel1);
        jTabbedPane1.putClientProperty("JTabbedPane.trailingComponent", trailingPanel);
        
        jTabbedPane2.putClientProperty("JTabbedPane.tabHeight", 50);
        jTabbedPane2.putClientProperty("JTabbedPane.tabAreaAlignment", "fill");
        
        scaleButtonIcon(back);
        scaleButtonIcon(settings);
        
        settingPanel.setVisible(false);
        
        setUpPresenceRecapTable();
        loadPresenceRecapDataDummy();
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton back;
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton5;
    private javax.swing.JComboBox<String> jComboBox1;
    private javax.swing.JComboBox<String> jComboBox2;
    private javax.swing.JComboBox<String> jComboBox4;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JPanel jPanel5;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JScrollPane jScrollPane3;
    private javax.swing.JScrollPane jScrollPane4;
    private javax.swing.JScrollPane jScrollPane5;
    private javax.swing.JTabbedPane jTabbedPane1;
    private javax.swing.JTabbedPane jTabbedPane2;
    private javax.swing.JTable jTable1;
    private javax.swing.JTable jTable2;
    private javax.swing.JToggleButton jToggleButton8;
    private javax.swing.JDesktopPane layer;
    private javax.swing.JLabel myProfile;
    private javax.swing.JPanel presencePanel;
    private javax.swing.JButton presencePanelSaveButton;
    private javax.swing.JComboBox<String> presencePanelSectionList;
    private javax.swing.JPanel presenceRecapPanel;
    private javax.swing.JButton presenceRecapPanelPrintButton;
    private javax.swing.JComboBox<String> presenceRecapSectionList;
    private javax.swing.JTable presenceRecapTable;
    private javax.swing.JTable presenceTable;
    private javax.swing.JPanel scorePanel;
    private javax.swing.JButton scorePanelPrintButton;
    private javax.swing.JButton scorePanelSaveButton;
    private javax.swing.JComboBox<String> scorePanelSectionList;
    private javax.swing.JTable scoreTable;
    private javax.swing.JInternalFrame settingPanel;
    private javax.swing.JLabel settingPanelBirthplaceLabel;
    private javax.swing.JPasswordField settingPanelConfirmNewPassword;
    private javax.swing.JComboBox<String> settingPanelDate;
    private com.unindra.school.app.components.RegionComboBox settingPanelDistrictList;
    private javax.swing.JTextField settingPanelEmailField;
    private javax.swing.JLabel settingPanelEmailLabel;
    private javax.swing.JLabel settingPanelGenderLabel;
    private javax.swing.JComboBox<String> settingPanelGenderList;
    private javax.swing.JComboBox<String> settingPanelMonth;
    private javax.swing.JTextField settingPanelNameField;
    private javax.swing.JLabel settingPanelNameLabel;
    private javax.swing.JPasswordField settingPanelPasswordField;
    private javax.swing.JLabel settingPanelPasswordLabel;
    private javax.swing.JTextField settingPanelPhoneNumberField;
    private javax.swing.JLabel settingPanelPhoneNumberLabel;
    private com.unindra.school.app.components.RegionComboBox settingPanelProvinceList;
    private com.unindra.school.app.components.RegionComboBox settingPanelRegencyList;
    private javax.swing.JTextField settingPanelUsernameField;
    private javax.swing.JLabel settingPanelUsernameLabel;
    private javax.swing.JComboBox<String> settingPanelYear;
    private javax.swing.JPasswordField settingPanelnewPassword;
    private javax.swing.JToggleButton settings;
    // End of variables declaration//GEN-END:variables
}
