/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package com.unindra.school.app.view;

import com.formdev.flatlaf.FlatDarkLaf;
import com.formdev.flatlaf.FlatLightLaf;
import com.formdev.flatlaf.themes.FlatMacDarkLaf;
import com.formdev.flatlaf.themes.FlatMacLightLaf;
import com.formdev.flatlaf.util.SystemInfo;
import com.unindra.school.app.util.AppManager;
import com.unindra.school.app.view.staff.StaffLoginView;
import com.unindra.school.app.view.teacher.TeacherLoginView;

import java.awt.Image;
import java.io.IOException;
import java.util.Locale;
import java.util.ResourceBundle;
import java.util.logging.Level;
import java.util.logging.Logger;

import javax.swing.Icon;
import javax.swing.ImageIcon;
import javax.swing.JButton;
import javax.swing.JDialog;
import javax.swing.JFrame;
import javax.swing.JToggleButton;
import javax.swing.SwingUtilities;
import javax.swing.UIManager;

/**
 *
 * @author rizmakiana
 */
public class SelectRoleView extends javax.swing.JFrame {

    /**
     * Creates new form SelectRoleView
     */
    public SelectRoleView() {
        generateComponent();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        corner = new javax.swing.JLabel();
        image = new javax.swing.JLabel();
        greeting = new javax.swing.JLabel();
        card = new javax.swing.JDesktopPane();
        logo = new javax.swing.JLabel();
        titleApp = new javax.swing.JLabel();
        selectRole = new javax.swing.JLabel();
        detail = new javax.swing.JLabel();
        detail2 = new javax.swing.JLabel();
        studentButton = new javax.swing.JButton();
        teacherButton = new javax.swing.JButton();
        staffButton = new javax.swing.JButton();
        settings2 = new javax.swing.JToggleButton();
        jDesktopPane1 = new javax.swing.JDesktopPane();
        jToggleButton1 = new javax.swing.JToggleButton();
        jComboBox1 = new javax.swing.JComboBox<>();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setUndecorated(true);
        setResizable(false);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());
        getContentPane().add(corner, new org.netbeans.lib.awtextra.AbsoluteConstraints(1270, 710, 10, 10));

        image.setIcon(new javax.swing.ImageIcon(getClass().getResource("/image/flat-student.png"))); // NOI18N
        getContentPane().add(image, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 250, 400, 400));

        greeting.setFont(new java.awt.Font("sansserif", 0, 32)); // NOI18N
        greeting.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        getContentPane().add(greeting, new org.netbeans.lib.awtextra.AbsoluteConstraints(180, 70, 300, 50));

        javax.swing.GroupLayout cardLayout = new javax.swing.GroupLayout(card);
        card.setLayout(cardLayout);
        cardLayout.setHorizontalGroup(
            cardLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 620, Short.MAX_VALUE)
        );
        cardLayout.setVerticalGroup(
            cardLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 680, Short.MAX_VALUE)
        );

        getContentPane().add(card, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 20, 620, 680));

        logo.setIcon(new javax.swing.ImageIcon(getClass().getResource("/image/logo.png"))); // NOI18N
        getContentPane().add(logo, new org.netbeans.lib.awtextra.AbsoluteConstraints(762, 58, 100, 100));

        titleApp.setFont(new java.awt.Font("sansserif", 0, 32)); // NOI18N
        getContentPane().add(titleApp, new org.netbeans.lib.awtextra.AbsoluteConstraints(872, 64, -1, -1));

        selectRole.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        getContentPane().add(selectRole, new org.netbeans.lib.awtextra.AbsoluteConstraints(770, 250, 400, 40));

        detail.setFont(new java.awt.Font("sansserif", 0, 20)); // NOI18N
        detail.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        getContentPane().add(detail, new org.netbeans.lib.awtextra.AbsoluteConstraints(700, 325, 540, 30));

        detail2.setFont(new java.awt.Font("sansserif", 0, 20)); // NOI18N
        detail2.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        detail2.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        getContentPane().add(detail2, new org.netbeans.lib.awtextra.AbsoluteConstraints(700, 355, 540, 30));

        studentButton.setFont(new java.awt.Font("sansserif", 0, 14)); // NOI18N
        getContentPane().add(studentButton, new org.netbeans.lib.awtextra.AbsoluteConstraints(820, 400, 300, 40));

        teacherButton.setFont(new java.awt.Font("sansserif", 0, 14)); // NOI18N
        teacherButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                teacherButtonActionPerformed(evt);
            }
        });
        getContentPane().add(teacherButton, new org.netbeans.lib.awtextra.AbsoluteConstraints(820, 450, 300, 40));

        staffButton.setFont(new java.awt.Font("sansserif", 0, 14)); // NOI18N
        staffButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                staffButtonActionPerformed(evt);
            }
        });
        getContentPane().add(staffButton, new org.netbeans.lib.awtextra.AbsoluteConstraints(820, 500, 300, 40));

        settings2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/image/settings.png"))); // NOI18N
        settings2.addChangeListener(new javax.swing.event.ChangeListener() {
            public void stateChanged(javax.swing.event.ChangeEvent evt) {
                settings2StateChanged(evt);
            }
        });
        getContentPane().add(settings2, new org.netbeans.lib.awtextra.AbsoluteConstraints(1200, 640, 40, 40));

        jToggleButton1.setText("jToggleButton1");
        jToggleButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jToggleButton1ActionPerformed(evt);
            }
        });

        jComboBox1.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "English (US)", "Bahasa Indonesia" }));
        jComboBox1.addItemListener(new java.awt.event.ItemListener() {
            public void itemStateChanged(java.awt.event.ItemEvent evt) {
                jComboBox1ItemStateChanged(evt);
            }
        });

        jDesktopPane1.setLayer(jToggleButton1, javax.swing.JLayeredPane.DEFAULT_LAYER);
        jDesktopPane1.setLayer(jComboBox1, javax.swing.JLayeredPane.DEFAULT_LAYER);

        javax.swing.GroupLayout jDesktopPane1Layout = new javax.swing.GroupLayout(jDesktopPane1);
        jDesktopPane1.setLayout(jDesktopPane1Layout);
        jDesktopPane1Layout.setHorizontalGroup(
            jDesktopPane1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jDesktopPane1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jComboBox1, javax.swing.GroupLayout.PREFERRED_SIZE, 212, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jToggleButton1, javax.swing.GroupLayout.PREFERRED_SIZE, 140, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );
        jDesktopPane1Layout.setVerticalGroup(
            jDesktopPane1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jDesktopPane1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jDesktopPane1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jToggleButton1)
                    .addComponent(jComboBox1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(9, Short.MAX_VALUE))
        );

        getContentPane().add(jDesktopPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(820, 640, 370, 40));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jToggleButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jToggleButton1ActionPerformed
        
        try {
            if (jToggleButton1.isSelected()) {
                AppManager.setLightMode(false);
                jToggleButton1.setText(setInternationalization("darkTheme"));
            } else {
                AppManager.setLightMode(true);
                jToggleButton1.setText(setInternationalization("lightTheme"));
            }

        } catch (Exception e) {
            e.printStackTrace();
        }
        // SwingUtilities.updateComponentTreeUI(this);
        
    }//GEN-LAST:event_jToggleButton1ActionPerformed

    private void jComboBox1ItemStateChanged(java.awt.event.ItemEvent evt) {//GEN-FIRST:event_jComboBox1ItemStateChanged
        
        if (jComboBox1.getSelectedIndex() == 1){
            AppManager.setLocale(Locale.forLanguageTag("id-ID"));
            // Locale.setDefault(Locale.forLanguageTag("id-ID"));
        } else {
            // Locale.setDefault(Locale.forLanguageTag("en-US"));
            AppManager.setLocale(Locale.forLanguageTag("en-US"));
        }
        initInternationalization();
    }//GEN-LAST:event_jComboBox1ItemStateChanged

    private void staffButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_staffButtonActionPerformed
        
        try {
            StaffLoginView view = new StaffLoginView();
            view.setVisible(true);
            
            this.dispose();
        } catch (IOException ex) {
            Logger.getLogger(SelectRoleView.class.getName()).log(Level.SEVERE, null, ex);
        }
        
    }//GEN-LAST:event_staffButtonActionPerformed

    private void teacherButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_teacherButtonActionPerformed
        
        try {
            TeacherLoginView view = new TeacherLoginView();
            view.setVisible(true);
            
            this.dispose();
        } catch (IOException ex) {
            Logger.getLogger(SelectRoleView.class.getName()).log(Level.SEVERE, null, ex);
        }
        
    }//GEN-LAST:event_teacherButtonActionPerformed

    private void settings2StateChanged(javax.swing.event.ChangeEvent evt) {// GEN-FIRST:event_settings2StateChanged

        if (settings2.isSelected()) {
            jDesktopPane1.setVisible(true);
        } else {
            jDesktopPane1.setVisible(false);
        }

    }// GEN-LAST:event_settings2StateChanged

    public void setImage(javax.swing.JLabel label) {

        Icon icon = label.getIcon();
        if (icon == null || !(icon instanceof ImageIcon)) {
            return; // kalau tidak ada icon, tidak perlu diproses
        }

        ImageIcon imageIcon = (ImageIcon) icon;

        // Resize gambar sesuai ukuran label
        Image image = imageIcon.getImage().getScaledInstance(
                label.getWidth(),
                label.getHeight(),
                Image.SCALE_SMOOTH);

        // Set icon hasil resize ke label
        label.setIcon(new ImageIcon(image));

    }

    public void scaleButtonIcon(JToggleButton button) {
        if (button.getIcon() != null && button.getIcon() instanceof ImageIcon) {
            int width = button.getWidth();
            int height = button.getHeight();

            // Kalau belum punya ukuran (belum render), pakai preferred size
            if (width <= 0 || height <= 0) {
                width = button.getPreferredSize().width;
                height = button.getPreferredSize().height;
            }

            ImageIcon originalIcon = (ImageIcon) button.getIcon();
            Image scaledImage = originalIcon.getImage()
                    .getScaledInstance(width - 15, height - 15, Image.SCALE_SMOOTH);

            button.setIcon(new ImageIcon(scaledImage));
        }
    }

    public String setInternationalization(String key) {

        ResourceBundle bundle = ResourceBundle.getBundle("message", AppManager.getLocale());

        return bundle.getString(key);
    }

    public void initInternationalization() {
        String line1 = setInternationalization("app.title1");
        String line2 = setInternationalization("app.title2");
        titleApp.setText(String.format("<html> %s <br> %s</html>", line1, line2));

        detail.setText(setInternationalization("selectRoleDesc1"));
        detail2.setText(setInternationalization("selectRoleDesc2"));
        greeting.setText(setInternationalization("welcome"));

        studentButton.setText(setInternationalization("student.text"));
        teacherButton.setText(setInternationalization("teacher.text"));
        staffButton.setText(setInternationalization("staff.text"));
        jToggleButton1.setText(setInternationalization("lightTheme"));
    }

    public void generateComponent() {
        initComponents();   
        initInternationalization();
        setLocationRelativeTo(null);
        setImage(image);
        scaleButtonIcon(settings2);
        jDesktopPane1.setVisible(false);
        boolean lightMode = AppManager.getLightMode();

        if (lightMode) {
            jToggleButton1.setSelected(false);
            jToggleButton1.setText(setInternationalization("lightTheme"));
        } else {
            jToggleButton1.setSelected(true);
            jToggleButton1.setText(setInternationalization("darkTheme"));
        }
        
        if (AppManager.getLocale().getLanguage().equals("en")) {
            jComboBox1.setSelectedIndex(0);
        } else {
            jComboBox1.setSelectedIndex(1);
        }
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JDesktopPane card;
    private javax.swing.JLabel corner;
    private javax.swing.JLabel detail;
    private javax.swing.JLabel detail2;
    private javax.swing.JLabel greeting;
    private javax.swing.JLabel image;
    private javax.swing.JComboBox<String> jComboBox1;
    private javax.swing.JDesktopPane jDesktopPane1;
    private javax.swing.JToggleButton jToggleButton1;
    private javax.swing.JLabel logo;
    private javax.swing.JLabel selectRole;
    private javax.swing.JToggleButton settings2;
    private javax.swing.JButton staffButton;
    private javax.swing.JButton studentButton;
    private javax.swing.JButton teacherButton;
    private javax.swing.JLabel titleApp;
    // End of variables declaration//GEN-END:variables
}
