/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package com.unindra.school.app.view.staff;

import com.unindra.school.app.view.teacher.*;
import com.formdev.flatlaf.ui.FlatTextAreaUI;
import com.unindra.school.app.view.staff.*;
import com.unindra.school.app.entity.StaffResponse;
import com.unindra.school.app.model.util.Gender;
import com.unindra.school.app.model.request.LoginRequest;
import com.unindra.school.app.model.response.RegionResponse;
import com.unindra.school.app.model.request.RegisterStaffRequest;
import com.unindra.school.app.service.AuthService;
import com.unindra.school.app.util.ComboBoxUtil;
import com.unindra.school.app.service.RegionService;
import com.unindra.school.app.service.StaffService;

import java.awt.Image;
import java.time.Month;
import java.time.Year;
import java.time.format.TextStyle;
import java.util.Arrays;
import java.util.ResourceBundle;
import java.util.stream.IntStream;

import javax.swing.DefaultComboBoxModel;
import javax.swing.ImageIcon;
import javax.swing.JToggleButton;

import com.unindra.school.app.util.AppManager;
import com.unindra.school.app.view.SelectRoleView;
import java.awt.event.ItemEvent;
import java.io.IOException;
import java.util.List;

import java.util.Locale;
import java.util.Optional;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JButton;
import javax.swing.JOptionPane;

/**
 *
 * @author rizmakiana
 */
public class StaffLoginView extends javax.swing.JFrame {

    RegionService regionService = new RegionService();
    /**
     * Creates new form StaffLoginView
     */
    public StaffLoginView() throws IOException {
        generateComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jTabbedPane1 = new javax.swing.JTabbedPane();
        signInPanel = new javax.swing.JPanel();
        signInLabel = new javax.swing.JLabel();
        signInusernameField = new javax.swing.JTextField();
        signInpasswordField = new javax.swing.JPasswordField();
        signInButton = new javax.swing.JButton();
        signInUsernameLabel = new javax.swing.JLabel();
        signInPasswordLabel = new javax.swing.JLabel();
        signInShowPassword = new javax.swing.JCheckBox();
        registerPanel = new javax.swing.JPanel();
        jScrollPane2 = new javax.swing.JScrollPane();
        jPanel1 = new javax.swing.JPanel();
        corner = new javax.swing.JLabel();
        registerLabel = new javax.swing.JLabel();
        registerNameLabel = new javax.swing.JLabel();
        registerNameField = new javax.swing.JTextField();
        registerGenderLabel = new javax.swing.JLabel();
        registerGenderField = new javax.swing.JComboBox<>();
        registerBirthplaceLabel = new javax.swing.JLabel();
        registerBirthdateLabel = new javax.swing.JLabel();
        registerDateField = new javax.swing.JComboBox<>();
        registerMonthField = new javax.swing.JComboBox<>();
        registerYearField = new javax.swing.JComboBox<>();
        registerUsernameField = new javax.swing.JTextField();
        registerAddressLabel = new javax.swing.JLabel();
        registerPasswordField = new javax.swing.JPasswordField();
        registerConfirmPasswordField = new javax.swing.JPasswordField();
        registerPasswordLabel = new javax.swing.JLabel();
        registerConfirmPasswordLabel = new javax.swing.JLabel();
        jScrollPane3 = new javax.swing.JScrollPane();
        registerAddressField = new javax.swing.JTextArea();
        registerUsernameLabel = new javax.swing.JLabel();
        registerEmailField = new javax.swing.JTextField();
        registerPhoneNumberField = new javax.swing.JTextField();
        registerEmailLabel = new javax.swing.JLabel();
        registerPhoneNumberLabel = new javax.swing.JLabel();
        registerButton = new javax.swing.JButton();
        registerProvinceBirthplace = new com.unindra.school.app.components.RegionComboBox();
        registerRegencyBirthplace = new com.unindra.school.app.components.RegionComboBox();
        registerAddressProvinceField = new com.unindra.school.app.components.RegionComboBox();
        registerAddressRegencyField = new com.unindra.school.app.components.RegionComboBox();
        registerAddressDistrictField = new com.unindra.school.app.components.RegionComboBox();
        setting = new javax.swing.JToggleButton();
        back = new javax.swing.JButton();
        jDesktopPane1 = new javax.swing.JDesktopPane();
        jToggleButton1 = new javax.swing.JToggleButton();
        jComboBox1 = new javax.swing.JComboBox<>();
        image = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        signInPanel.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        signInLabel.setFont(new java.awt.Font("sansserif", 1, 20)); // NOI18N
        signInLabel.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        signInPanel.add(signInLabel, new org.netbeans.lib.awtextra.AbsoluteConstraints(71, 120, 250, 35));
        signInPanel.add(signInusernameField, new org.netbeans.lib.awtextra.AbsoluteConstraints(46, 222, 300, 35));
        signInPanel.add(signInpasswordField, new org.netbeans.lib.awtextra.AbsoluteConstraints(46, 295, 300, 35));

        signInButton.setFont(new java.awt.Font("sansserif", 0, 16)); // NOI18N
        signInButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                signInButtonActionPerformed(evt);
            }
        });
        signInPanel.add(signInButton, new org.netbeans.lib.awtextra.AbsoluteConstraints(46, 400, 300, 35));

        signInUsernameLabel.setText("jLabel1");
        signInPanel.add(signInUsernameLabel, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 200, 150, 20));

        signInPasswordLabel.setText("jLabel1");
        signInPanel.add(signInPasswordLabel, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 275, 150, 20));

        signInShowPassword.setText("jCheckBox1");
        signInShowPassword.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                signInShowPasswordActionPerformed(evt);
            }
        });
        signInPanel.add(signInShowPassword, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 335, -1, -1));

        jTabbedPane1.addTab("tab1", signInPanel);

        jScrollPane2.setBorder(null);
        jScrollPane2.setHorizontalScrollBarPolicy(javax.swing.ScrollPaneConstants.HORIZONTAL_SCROLLBAR_NEVER);
        jScrollPane2.setViewportView(jPanel1);

        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());
        jPanel1.add(corner, new org.netbeans.lib.awtextra.AbsoluteConstraints(380, 800, -1, -1));

        registerLabel.setFont(new java.awt.Font("sansserif", 1, 20)); // NOI18N
        registerLabel.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jPanel1.add(registerLabel, new org.netbeans.lib.awtextra.AbsoluteConstraints(71, 30, 250, 40));

        registerNameLabel.setText("jLabel2");
        jPanel1.add(registerNameLabel, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 105, 150, -1));

        registerNameField.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                registerNameFieldKeyReleased(evt);
            }
        });
        jPanel1.add(registerNameField, new org.netbeans.lib.awtextra.AbsoluteConstraints(15, 125, 220, 35));

        registerGenderLabel.setText("label");
        jPanel1.add(registerGenderLabel, new org.netbeans.lib.awtextra.AbsoluteConstraints(245, 105, 120, -1));
        jPanel1.add(registerGenderField, new org.netbeans.lib.awtextra.AbsoluteConstraints(240, 125, 130, 35));

        registerBirthplaceLabel.setText("jLabel1");
        jPanel1.add(registerBirthplaceLabel, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 165, 150, -1));

        registerBirthdateLabel.setText("jLabel1");
        jPanel1.add(registerBirthdateLabel, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 225, 150, -1));

        registerDateField.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));
        jPanel1.add(registerDateField, new org.netbeans.lib.awtextra.AbsoluteConstraints(15, 245, 80, 35));

        registerMonthField.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));
        jPanel1.add(registerMonthField, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 245, 170, 35));

        registerYearField.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));
        jPanel1.add(registerYearField, new org.netbeans.lib.awtextra.AbsoluteConstraints(275, 245, 95, 35));
        jPanel1.add(registerUsernameField, new org.netbeans.lib.awtextra.AbsoluteConstraints(15, 510, 355, 35));

        registerAddressLabel.setText("jLabel1");
        jPanel1.add(registerAddressLabel, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 285, 150, -1));
        jPanel1.add(registerPasswordField, new org.netbeans.lib.awtextra.AbsoluteConstraints(15, 570, 175, 35));
        jPanel1.add(registerConfirmPasswordField, new org.netbeans.lib.awtextra.AbsoluteConstraints(195, 570, 175, 35));

        registerPasswordLabel.setText("jLabel2");
        jPanel1.add(registerPasswordLabel, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 550, 150, -1));

        registerConfirmPasswordLabel.setText("jLabel3");
        jPanel1.add(registerConfirmPasswordLabel, new org.netbeans.lib.awtextra.AbsoluteConstraints(200, 550, 150, -1));

        registerAddressField.setColumns(20);
        registerAddressField.setLineWrap(true);
        registerAddressField.setRows(5);
        registerAddressField.setWrapStyleWord(true);
        jScrollPane3.setViewportView(registerAddressField);

        jPanel1.add(jScrollPane3, new org.netbeans.lib.awtextra.AbsoluteConstraints(15, 385, 355, -1));

        registerUsernameLabel.setText("jLabel4");
        jPanel1.add(registerUsernameLabel, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 490, 150, -1));
        jPanel1.add(registerEmailField, new org.netbeans.lib.awtextra.AbsoluteConstraints(15, 630, 175, 35));
        jPanel1.add(registerPhoneNumberField, new org.netbeans.lib.awtextra.AbsoluteConstraints(195, 630, 175, 35));

        registerEmailLabel.setText("jLabel5");
        jPanel1.add(registerEmailLabel, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 610, 150, -1));

        registerPhoneNumberLabel.setText("jLabel6");
        jPanel1.add(registerPhoneNumberLabel, new org.netbeans.lib.awtextra.AbsoluteConstraints(200, 610, 150, -1));

        registerButton.setText("jButton1");
        registerButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                registerButtonActionPerformed(evt);
            }
        });
        jPanel1.add(registerButton, new org.netbeans.lib.awtextra.AbsoluteConstraints(15, 710, 355, 35));

        registerProvinceBirthplace.addItemListener(new java.awt.event.ItemListener() {
            public void itemStateChanged(java.awt.event.ItemEvent evt) {
                registerProvinceBirthplaceItemStateChanged(evt);
            }
        });
        jPanel1.add(registerProvinceBirthplace, new org.netbeans.lib.awtextra.AbsoluteConstraints(15, 185, 180, 35));
        jPanel1.add(registerRegencyBirthplace, new org.netbeans.lib.awtextra.AbsoluteConstraints(200, 185, 170, 35));

        registerAddressProvinceField.addItemListener(new java.awt.event.ItemListener() {
            public void itemStateChanged(java.awt.event.ItemEvent evt) {
                registerAddressProvinceFieldItemStateChanged(evt);
            }
        });
        jPanel1.add(registerAddressProvinceField, new org.netbeans.lib.awtextra.AbsoluteConstraints(15, 305, 355, 35));

        registerAddressRegencyField.addItemListener(new java.awt.event.ItemListener() {
            public void itemStateChanged(java.awt.event.ItemEvent evt) {
                registerAddressRegencyFieldItemStateChanged(evt);
            }
        });
        jPanel1.add(registerAddressRegencyField, new org.netbeans.lib.awtextra.AbsoluteConstraints(15, 345, 175, 35));
        jPanel1.add(registerAddressDistrictField, new org.netbeans.lib.awtextra.AbsoluteConstraints(195, 345, 175, 35));

        jScrollPane2.setViewportView(jPanel1);

        javax.swing.GroupLayout registerPanelLayout = new javax.swing.GroupLayout(registerPanel);
        registerPanel.setLayout(registerPanelLayout);
        registerPanelLayout.setHorizontalGroup(
            registerPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 390, javax.swing.GroupLayout.PREFERRED_SIZE)
        );
        registerPanelLayout.setVerticalGroup(
            registerPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(registerPanelLayout.createSequentialGroup()
                .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 610, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );

        jTabbedPane1.addTab("tab3", registerPanel);

        getContentPane().add(jTabbedPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 392, 650));

        setting.setIcon(new javax.swing.ImageIcon(getClass().getResource("/image/settings.png"))); // NOI18N
        setting.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                settingActionPerformed(evt);
            }
        });
        getContentPane().add(setting, new org.netbeans.lib.awtextra.AbsoluteConstraints(65, 660, 40, 40));

        back.setIcon(new javax.swing.ImageIcon(getClass().getResource("/image/return.png"))); // NOI18N
        back.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                backActionPerformed(evt);
            }
        });
        getContentPane().add(back, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 660, 40, 40));

        jToggleButton1.setText("jToggleButton1");
        jToggleButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jToggleButton1ActionPerformed(evt);
            }
        });

        jComboBox1.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "English (US)", "Bahasa Indonesia" }));
        jComboBox1.addItemListener(new java.awt.event.ItemListener() {
            public void itemStateChanged(java.awt.event.ItemEvent evt) {
                jComboBox1ItemStateChanged(evt);
            }
        });

        jDesktopPane1.setLayer(jToggleButton1, javax.swing.JLayeredPane.DEFAULT_LAYER);
        jDesktopPane1.setLayer(jComboBox1, javax.swing.JLayeredPane.DEFAULT_LAYER);

        javax.swing.GroupLayout jDesktopPane1Layout = new javax.swing.GroupLayout(jDesktopPane1);
        jDesktopPane1.setLayout(jDesktopPane1Layout);
        jDesktopPane1Layout.setHorizontalGroup(
            jDesktopPane1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jDesktopPane1Layout.createSequentialGroup()
                .addGap(5, 5, 5)
                .addComponent(jToggleButton1, javax.swing.GroupLayout.PREFERRED_SIZE, 140, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(5, 5, 5)
                .addComponent(jComboBox1, javax.swing.GroupLayout.PREFERRED_SIZE, 212, javax.swing.GroupLayout.PREFERRED_SIZE))
        );
        jDesktopPane1Layout.setVerticalGroup(
            jDesktopPane1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jDesktopPane1Layout.createSequentialGroup()
                .addGap(7, 7, 7)
                .addGroup(jDesktopPane1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jToggleButton1)
                    .addComponent(jComboBox1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
        );

        getContentPane().add(jDesktopPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(110, 660, 370, 40));

        image.setIcon(new javax.swing.ImageIcon(getClass().getResource("/image/image2.png"))); // NOI18N
        getContentPane().add(image, new org.netbeans.lib.awtextra.AbsoluteConstraints(392, 0, 888, 720));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void signInShowPasswordActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_signInShowPasswordActionPerformed

        if(signInShowPassword.isSelected()){
            signInpasswordField.setEchoChar((char) 0);
        } else {
            signInpasswordField.setEchoChar(AppManager.getDefaultPasswordChar());
        }

    }//GEN-LAST:event_signInShowPasswordActionPerformed

    private void signInButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_signInButtonActionPerformed
        
        
        String username = signInusernameField.getText();
        String password = new String(signInpasswordField.getPassword());
          
        LoginRequest request = new LoginRequest(username, password);
          
        try {
            String response = new AuthService().loginStaff(request);
            
            StaffResponse staff = new AuthService().getCurrentStaff();
              
            JOptionPane.showMessageDialog(this, response, setInternationalization("success"), JOptionPane.PLAIN_MESSAGE);
            
            try {
//                StaffResponse staff = new StaffResponse();
                //StaffDashboardView view = new StaffDashboardView(staff);
                StaffDashboardView view = new StaffDashboardView(staff);
                view.setVisible(true);
            
                this.dispose();

            } catch (Exception e) {
                e.printStackTrace();
            }
            
        } catch (IOException e) {
            JOptionPane.showMessageDialog(this, e.getMessage(), setInternationalization("error"), JOptionPane.ERROR_MESSAGE);
        }
        
        
    }//GEN-LAST:event_signInButtonActionPerformed

    private void registerNameFieldKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_registerNameFieldKeyReleased
        
        registerUsernameField.setText(registerNameField.getText().replace(" ", "").replace("-", "").toLowerCase());
        
    }//GEN-LAST:event_registerNameFieldKeyReleased

    private void registerProvinceBirthplaceItemStateChanged(java.awt.event.ItemEvent evt) {//GEN-FIRST:event_registerProvinceBirthplaceItemStateChanged
        
        try {
            registerRegencyBirthplace.setItems(regionService.getRegencies(registerProvinceBirthplace.getSelectedRegion().getId()));
        } catch (IOException ex) {
            Logger.getLogger(StaffLoginView.class.getName()).log(Level.SEVERE, null, ex);
        }
        
    }//GEN-LAST:event_registerProvinceBirthplaceItemStateChanged

    private void registerAddressProvinceFieldItemStateChanged(java.awt.event.ItemEvent evt) {//GEN-FIRST:event_registerAddressProvinceFieldItemStateChanged
        
        try {
            registerAddressRegencyField.setItems(regionService.getRegencies(registerAddressProvinceField.getSelectedRegion().getId()));
            registerAddressDistrictField.setItems(regionService.getDistricts(registerAddressRegencyField.getSelectedRegion().getId()));
        } catch (IOException ex) {
            Logger.getLogger(StaffLoginView.class.getName()).log(Level.SEVERE, null, ex);
        }
        
    }//GEN-LAST:event_registerAddressProvinceFieldItemStateChanged

    private void registerAddressRegencyFieldItemStateChanged(java.awt.event.ItemEvent evt) {//GEN-FIRST:event_registerAddressRegencyFieldItemStateChanged
        
        if (evt.getStateChange() != ItemEvent.SELECTED) {
            return;
        }

        Object item = evt.getItem();
        if (!(item instanceof RegionResponse region)) {
            return;
        }

        try {
            registerAddressDistrictField.setItems(regionService.getDistricts(region.getId()));
        } catch (IOException ex) {
            Logger.getLogger(StaffLoginView.class.getName()).log(Level.SEVERE, null, ex);
        }
             
    }//GEN-LAST:event_registerAddressRegencyFieldItemStateChanged

    private void registerButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_registerButtonActionPerformed
        
        RegisterStaffRequest request = new RegisterStaffRequest();
       
       request.setName(registerNameField.getText());
       Gender g = (registerGenderField.getSelectedIndex() == 0) ? Gender.MALE : Gender.FEMALE;
       request.setGender(g);
       request.setBirthPlaceRegency(registerAddressRegencyField.getSelectedRegion().getId());
       request.setBirthDate(registerDateField.getSelectedItem().toString());
       request.setBirthMonth(registerMonthField.getSelectedIndex() + 1);
       request.setBirthYear(registerYearField.getSelectedItem().toString());
       request.setDistrictAddress(registerAddressDistrictField.getSelectedRegion().getId());
       request.setAddress(registerAddressField.getText());
       request.setUsername(registerUsernameField.getText());
       request.setPassword(new String (registerPasswordField.getPassword()));
       request.setConfirmPassword(new String (registerConfirmPasswordField.getPassword()));
       request.setEmail(registerEmailField.getText());
       request.setPhoneNumber(registerPhoneNumberField.getText());
        
        StaffService service = new StaffService();
        
        try {
            
            String response = service.register(request);
            
            JOptionPane.showMessageDialog(this, response, setInternationalization("success"), JOptionPane.PLAIN_MESSAGE);
            clearFormRegistration();
        } catch (IOException e) {
            JOptionPane.showMessageDialog(this, e.getMessage(), setInternationalization("error"), JOptionPane.ERROR_MESSAGE);
        }
        
    }//GEN-LAST:event_registerButtonActionPerformed

    private void setupRegionComboBox() throws IOException{
        
        registerProvinceBirthplace.setItems(regionService.getProvinces());
        registerRegencyBirthplace.setItems(regionService.getRegencies(registerProvinceBirthplace.getSelectedRegion().getId()));
        
        registerAddressProvinceField.setItems(regionService.getProvinces());
        registerAddressRegencyField.setItems(regionService.getRegencies(registerAddressProvinceField.getSelectedRegion().getId()));
        registerAddressDistrictField.setItems(regionService.getDistricts(registerAddressRegencyField.getSelectedRegion().getId()));

    }
    
    private void backActionPerformed(java.awt.event.ActionEvent evt) {// GEN-FIRST:event_backActionPerformed

        SelectRoleView view = new SelectRoleView();
        view.setVisible(true);

        this.dispose();

    }// GEN-LAST:event_backActionPerformed

    private void settingActionPerformed(java.awt.event.ActionEvent evt) {// GEN-FIRST:event_settingActionPerformed

        if (setting.isSelected()) {
            jDesktopPane1.setVisible(true);
        } else {
            jDesktopPane1.setVisible(false);
        }

    }// GEN-LAST:event_settingActionPerformed

    private void jToggleButton1ActionPerformed(java.awt.event.ActionEvent evt) {// GEN-FIRST:event_jToggleButton1ActionPerformed

        try {
            if (jToggleButton1.isSelected()) {
                AppManager.setLightMode(false);
                jToggleButton1.setText(setInternationalization("darkTheme"));
            } else {
                AppManager.setLightMode(true);
                jToggleButton1.setText(setInternationalization("lightTheme"));
            }

        } catch (Exception e) {
            e.printStackTrace();
        }

    }// GEN-LAST:event_jToggleButton1ActionPerformed

    private void jComboBox1ItemStateChanged(java.awt.event.ItemEvent evt) {// GEN-FIRST:event_jComboBox1ItemStateChanged

        if (jComboBox1.getSelectedIndex() == 1) {
            AppManager.setLocale(Locale.forLanguageTag("id-ID"));
        } else {
            AppManager.setLocale(Locale.forLanguageTag("en-US"));
        }
        initInternationalization();

    }// GEN-LAST:event_jComboBox1ItemStateChanged

    private void clearFormRegistration(){
        registerNameField.setText("");
        registerGenderField.setSelectedIndex(0);
        registerUsernameField.setText("");
        registerPasswordField.setText("");
        registerConfirmPasswordField.setText("");
        registerDateField.setSelectedIndex(0);
        registerMonthField.setSelectedIndex(0);
        registerYearField.setSelectedItem("");
        registerEmailField.setText("");
        registerPhoneNumberField.setText("");
    }
    
    public void scaleButtonIcon(JToggleButton button) {
        if (button.getIcon() != null && button.getIcon() instanceof ImageIcon) {
            int width = button.getWidth();
            int height = button.getHeight();

            // Kalau belum punya ukuran (belum render), pakai preferred size
            if (width <= 0 || height <= 0) {
                width = button.getPreferredSize().width;
                height = button.getPreferredSize().height;
            }

            ImageIcon originalIcon = (ImageIcon) button.getIcon();
            Image scaledImage = originalIcon.getImage()
                    .getScaledInstance(width - 15, height - 15, Image.SCALE_SMOOTH);

            button.setIcon(new ImageIcon(scaledImage));
        }
    }

    public void scaleButtonIcon(JButton button) {
        if (button.getIcon() != null && button.getIcon() instanceof ImageIcon) {
            int width = button.getWidth();
            int height = button.getHeight();

            // Kalau belum punya ukuran (belum render), pakai preferred size
            if (width <= 0 || height <= 0) {
                width = button.getPreferredSize().width;
                height = button.getPreferredSize().height;
            }

            ImageIcon originalIcon = (ImageIcon) button.getIcon();
            Image scaledImage = originalIcon.getImage()
                    .getScaledInstance(width - 15, height - 15, Image.SCALE_SMOOTH);

            button.setIcon(new ImageIcon(scaledImage));
        }
    }

    public String setInternationalization(String key) {

        ResourceBundle bundle = ResourceBundle.getBundle("message", AppManager.getLocale());

        return bundle.getString(key);
    }

    public void initInternationalization() {
        jTabbedPane1.setTitleAt(0, setInternationalization("login"));
        jTabbedPane1.setTitleAt(1, setInternationalization("register"));

        signInLabel.setText(setInternationalization("sign.in"));
        signInUsernameLabel.setText(setInternationalization("username"));
        signInPasswordLabel.setText(setInternationalization("password"));
        signInShowPassword.setText(setInternationalization("show.password"));
        signInButton.setText(setInternationalization("sign.in"));

        registerLabel.setText(setInternationalization("register"));
        registerButton.setText(setInternationalization("register"));

        registerNameLabel.setText(setInternationalization("full.name"));
        registerGenderLabel.setText(setInternationalization("gender"));
        String[] genders = new String[] { setInternationalization("male"), setInternationalization("female") };
        registerGenderField.setModel(new DefaultComboBoxModel<>(genders));
        registerBirthplaceLabel.setText(setInternationalization("birthplace"));
        registerBirthdateLabel.setText(setInternationalization("birthdate"));
        registerAddressLabel.setText(setInternationalization("address"));
        registerUsernameLabel.setText(setInternationalization("username"));
        registerPasswordLabel.setText(setInternationalization("password"));
        registerConfirmPasswordLabel.setText(setInternationalization("confirm.password"));
        registerEmailLabel.setText(setInternationalization("email"));
        registerPhoneNumberLabel.setText(setInternationalization("phone.number"));
        registerMonthField.setModel(new DefaultComboBoxModel<>(ComboBoxUtil.getMonthList()));
        
        boolean lightMode = AppManager.getLightMode();

        if (lightMode) {
            jToggleButton1.setSelected(false);
            jToggleButton1.setText(setInternationalization("lightTheme"));
        } else {
            jToggleButton1.setSelected(true);
            jToggleButton1.setText(setInternationalization("darkTheme"));
        }
    }

    public void generateComponents() throws IOException {
        initComponents();
        setLocationRelativeTo(null);
        initInternationalization();
        
        jTabbedPane1.putClientProperty("JTabbedPane.tabAreaAlignment", "fill");
        scaleButtonIcon(setting);
        scaleButtonIcon(back);
        registerDateField.setModel(new DefaultComboBoxModel<>(ComboBoxUtil.getDateList()));
        registerYearField.setModel(new DefaultComboBoxModel<>(ComboBoxUtil.getYearListTeacher()));

        boolean lightMode = AppManager.getLightMode();

        if (lightMode) {
            jToggleButton1.setSelected(false);
            jToggleButton1.setText(setInternationalization("lightTheme"));
        } else {
            jToggleButton1.setSelected(true);
            jToggleButton1.setText(setInternationalization("darkTheme"));
        }

        if (AppManager.getLocale().getLanguage().equals("en")) {
            jComboBox1.setSelectedIndex(0);
        } else {
            jComboBox1.setSelectedIndex(1);
        }

        jDesktopPane1.setVisible(false);
       
        setupRegionComboBox();
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton back;
    private javax.swing.JLabel corner;
    private javax.swing.JLabel image;
    private javax.swing.JComboBox<String> jComboBox1;
    private javax.swing.JDesktopPane jDesktopPane1;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JScrollPane jScrollPane3;
    private javax.swing.JTabbedPane jTabbedPane1;
    private javax.swing.JToggleButton jToggleButton1;
    private com.unindra.school.app.components.RegionComboBox registerAddressDistrictField;
    private javax.swing.JTextArea registerAddressField;
    private javax.swing.JLabel registerAddressLabel;
    private com.unindra.school.app.components.RegionComboBox registerAddressProvinceField;
    private com.unindra.school.app.components.RegionComboBox registerAddressRegencyField;
    private javax.swing.JLabel registerBirthdateLabel;
    private javax.swing.JLabel registerBirthplaceLabel;
    private javax.swing.JButton registerButton;
    private javax.swing.JPasswordField registerConfirmPasswordField;
    private javax.swing.JLabel registerConfirmPasswordLabel;
    private javax.swing.JComboBox<String> registerDateField;
    private javax.swing.JTextField registerEmailField;
    private javax.swing.JLabel registerEmailLabel;
    private javax.swing.JComboBox<String> registerGenderField;
    private javax.swing.JLabel registerGenderLabel;
    private javax.swing.JLabel registerLabel;
    private javax.swing.JComboBox<String> registerMonthField;
    private javax.swing.JTextField registerNameField;
    private javax.swing.JLabel registerNameLabel;
    private javax.swing.JPanel registerPanel;
    private javax.swing.JPasswordField registerPasswordField;
    private javax.swing.JLabel registerPasswordLabel;
    private javax.swing.JTextField registerPhoneNumberField;
    private javax.swing.JLabel registerPhoneNumberLabel;
    private com.unindra.school.app.components.RegionComboBox registerProvinceBirthplace;
    private com.unindra.school.app.components.RegionComboBox registerRegencyBirthplace;
    private javax.swing.JTextField registerUsernameField;
    private javax.swing.JLabel registerUsernameLabel;
    private javax.swing.JComboBox<String> registerYearField;
    private javax.swing.JToggleButton setting;
    private javax.swing.JButton signInButton;
    private javax.swing.JLabel signInLabel;
    private javax.swing.JPanel signInPanel;
    private javax.swing.JLabel signInPasswordLabel;
    private javax.swing.JCheckBox signInShowPassword;
    private javax.swing.JLabel signInUsernameLabel;
    private javax.swing.JPasswordField signInpasswordField;
    private javax.swing.JTextField signInusernameField;
    // End of variables declaration//GEN-END:variables
}
